#abc=("I like to play guiter and i am huge fan of sungha jung and he play very good guiter but never want to play")
#xyz=(abc.find("play"))
#print(xyz)
#a=(abc.find("play",xyz+1))
#print(a)
#b=((abc.find("play",a+1)),a+1)
#print(b)
#abc=("I like to play guiter and i am huge fan of sungha jung and he play very good guiter")
#xyz=(abc.find("play"))
#tuv=(abc.find("play",xyz+1))
#print(tuv)
#print(abc[tuv:])
#requesting input
#print("Hello")
#x=input("what is your name ")
#print("nice to meet you "+x)
#requesting input
print("Hello")
x=input("what is your name ")
print(x +" lenght of your name is " + str(len(x)))
y=input("what is your age: ")
print(("you past be ")+str(int(y)-1)+(" in a years"))
